### ISSUE TITLE
:curly_loop: Maintenance automation > Create PRs to self-maintain action :robot: 

### ISSUE THREAD

**Issue by adriens** [opt-nc/setup-duckdb-action#1]
# :grey_question: About

Actually the `duckdb` version runtime upgrade is manual **while   :duck: runs fast :sweat_smile: ** (see [code frequency](https://github.com/duckdb/duckdb/graphs/code-frequency)) : 

![image](https://user-images.githubusercontent.com/5235127/225207405-a4204e8c-7bab-4446-adf5-cdfae266d3ac.png)

# :bulb: The idea

**What we want is like a dependabot,** which, once a day : 

- Check if the actions'vs version is the latest one
- If not -> make a PR to upgrade it so we just have to review/release a new version

# :nerd_face: Resources

The following script makes it possible to get the latest release without any additional dependency (I guess `pyhton` available on GH ubuntu), based on Gh API:

```shell
echo "☎️ Get latest DuckDB release from duckdb/duckdb"
DUCKDB_VERSION=$(curl --silent -L \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/duckdb/duckdb/releases/latest |\
  python3 -c 'import json,sys;print(json.load(sys.stdin)["tag_name"])')
echo "$DUCKDB_VERSION"
```

:point_up: It's even ~~easier~~ shorter with `jq` : 

```shell
DUCKDB_VERSION=$(curl --silent -L \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/duckdb/duckdb/releases/latest |\
  jq '.tag_name')
echo $DUCKDB_VERSION
```

**Comment by adriens** [comment]
:bulb:  ...maybe will you rather do it from `js`

**Comment by mbarre** [comment]
1rst step, display warning message in logs :heavy_check_mark:

**Comment by mbarre** [comment]
> Check if the actions'vs version is the latest one

I guess you would like to write "Check if the DuckDB version is the latest one"  ?
