### ISSUE TITLE
:name_badge:  "Release failing" badge :broken_heart: 

### ISSUE THREAD

**Issue by adriens** [opt-nc/setup-duckdb-action#39]
![image](https://github.com/opt-nc/setup-duckdb-action/assets/5235127/c020f1a6-ef45-490f-a742-e9f24cf11f15)

**Comment by mbarre** [comment]
Depuis les derniere version de semantic release et @semanticrelease/releasenotegenerator, il y a des incompatibilités de version.
Je supprime temporairement @semanticrelease/releasenotegenerator,
