### ISSUE TITLE
:bulb: DUCKDB_VERSION version as Github variable :zap: 

### ISSUE THREAD

**Issue by adriens** [opt-nc/setup-duckdb-action#6]
# :grey_question: About

The action currently needs to get a [hard coded duckdb version to be setup in the worfflow setup](https://github.com/marketplace/actions/duckdb-setup) :

![image](https://user-images.githubusercontent.com/5235127/226216429-96bcbafd-4040-4195-90a6-17182ae3b8bb.png)

But recently, [GitHub Actions Support for configuration variables in workflows](https://github.blog/changelog/2023-01-10-github-actions-support-for-configuration-variables-in-workflows/) : 

> "Configuration variables allows you to store your non sensitive data as plain text variables that can be reused across your workflows in your repository or organization. 
> You can define variables at Organization, Repository or Environment level based on your requirement." 

![image](https://user-images.githubusercontent.com/5235127/226216507-19f7650d-38a1-4413-87aa-90c7f797f65f.png)

# :dart: Feature request

Proposed workflow : 

- **`version` is provided when calling the action** :arrow_right:  then this version is used. :stop_button: 
- **`version` is NOT provided** in the action call ↩️
    1. There is a **local variable** called `DUCKDB_VERSION` :arrow_right: then `DUCKDB_VERSION` is used (from the local repo scope) :stop_button: 
    2. There is a **global variable** called `DUCKDB_VERSION` :arrow_right: then `DUCKDB_VERSION` is used (from the global scope) :stop_button: 
    3. **ELSE** :arrow_right: the latest version will be installed. :stop_button: 

# :moneybag: Benefits

It **makes it possible to ( if you need to)** : 

- :heavy_check_mark: Stay up-to-date **by default** (effortless... **probably the default mode**)
- :heavy_check_mark: Stick to any **specific version at the repo level** (useful **in case you need to stick to a version**, eg. for regressions)
- :heavy_check_mark: Ttick to any specific **version at the org level level** (useful **in case you need to stick to a version**, eg. for regressions)

# :bookmark: Resources

- [:memo:  Variables](https://docs.github.com/en/actions/learn-github-actions/variables)
- [:newspaper:  GitHub Actions Support for configuration variables in workflows](https://github.blog/changelog/2023-01-10-github-actions-support-for-configuration-variables-in-workflows/)

**Comment by mbarre** [comment]
Il faut etre admin de la repo pour utiliser l'api des variables,

![Image](https://user-images.githubusercontent.com/1823161/231018309-9f80fd1f-5cdd-41f2-8387-12c6dda0ee6f.png)

**Comment by adriens** [comment]
... you mean when you deploy the action on a new orga ?

**Comment by mbarre** [comment]
yes

**Comment by mbarre** [comment]
@adriens, should I close this issue ?
