### ISSUE TITLE
:grey_question: Validate action to install latest v0.9.1

### ISSUE THREAD

**Issue by adriens** [opt-nc/setup-duckdb-action#65]
# :grey_question: About

duckdb [`v0.9.1`](https://github.com/duckdb/duckdb/releases/tag/v0.9.1) :grey_question:  is out on : 

- core engine
- [MotherDuck](https://motherduck.com/)
- [Tad](https://twitter.com/TadViewer/status/1714504455935385961) compatible

![image](https://github.com/opt-nc/setup-duckdb-action/assets/5235127/c54c9173-c15b-43ef-a7a2-537766e65a80)

**:point_right: We need to ensure this new version, approagching the `1.x` branch is fully usable with the action.**

# :dart: Question

Does the action support this [`v0.9.1`](https://github.com/duckdb/duckdb/releases/tag/v0.9.1) :grey_question:

**Comment by mbarre** [comment]
![image](https://github.com/opt-nc/setup-duckdb-action/assets/1823161/dfb399d3-1a47-4333-830a-f50275ec4b68)

**Comment by adriens** [comment]
:+1:  Upgraded at the org level for all our actions
![image](https://github.com/opt-nc/setup-duckdb-action/assets/5235127/4c670399-d600-45f0-b198-f45cf96f5bb4)
