### ISSUE TITLE
:information_source: Enhance the About fo the repo

### ISSUE THREAD

**Issue by adriens** [opt-nc/setup-duckdb-action#7]
Current desc: 

![image](https://user-images.githubusercontent.com/5235127/226217780-f58466e0-240b-447a-8d41-f1ab9677e5a4.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/226218170-91279ea5-468d-4bc9-ae70-944d1b712ce0.png)

**Comment by adriens** [comment]
:hand: @mbarre , shouldn't we remove the `Environment` :thought_balloon: 

![image](https://user-images.githubusercontent.com/5235127/226218415-1c2c2813-6c48-49cd-a293-bf32322541e9.png)
`

**Comment by adriens** [comment]
I have cloned labels from duckdb too

**Comment by mbarre** [comment]
done

**Comment by adriens** [comment]
:zap:
