### ISSUE TITLE
:shopping: Better tags for marketplace

### ISSUE THREAD

**Issue by adriens** [opt-nc/setup-duckdb-action#8]
# :grey_question: About

Actually there are a very few tags : 

![image](https://user-images.githubusercontent.com/5235127/226218530-09b8f583-b7ab-477a-b9a1-58e5ace61304.png)

# :dart: Action

Could we import some of the About : 

- #7

**Comment by mbarre** [comment]
Vu ensemble, la liste des tags est minimaliste

**Comment by adriens** [comment]
yes madame :pray:
